### ISSUE TITLE
carousel cards not of same size

### ISSUE THREAD

**Issue by kuchlous** [PrathamBooks/frp#106]
Check on donateabook.org.in
![screen shot 2015-06-03 at 4 30 28 pm](https://cloud.githubusercontent.com/assets/1202539/7958527/ea315e46-0a0d-11e5-888d-93f4a5c5c5e8.png)

**Comment by pvsandeep** [comment]
Update line no: 12526

#geography .col-md-4 p {
  min-height: 234px;
  height: 234px;
  overflow: auto;
}

[image: Inline image 1]

On Wed, Jun 3, 2015 at 9:07 PM, AK <notifications@github.com> wrote:

> Assigned #106 <https://github.com/PrathamBooks/frp/issues/106> to
> @pvsandeep <https://github.com/pvsandeep>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/106#event-321433159>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
Thanks. Works.
