### ISSUE TITLE
unaligned different sized boxes

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#108]
Boxes on the Donate page not aligned. 

![image](https://cloud.githubusercontent.com/assets/12147445/7978241/c9ceb1aa-0ab0-11e5-8478-376d86dc25dc.png)

**Comment by pvsandeep** [comment]
*line-no: 9948*
#campaigns .col-md-3 .campaignInfo p {
    height: 244px;
    min-height: 245px;
    overflow: auto;
}


*line-no: 10247*

#internalCampaign #campaigns .col-md-3 h2 {
    min-height: 60px;
}


.internal .col-md-9 .campaignInfo > ul {
    height: 120px;
    min-height: 118px;
    overflow: auto;
}

On Thu, Jun 4, 2015 at 12:22 PM, AK <notifications@github.com> wrote:

> Assigned #108 <https://github.com/PrathamBooks/frp/issues/108> to
> @pvsandeep <https://github.com/pvsandeep>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/108#event-322143371>.
>



-- 
Thanks,
Sandeep
