### ISSUE TITLE
Admin Dashboard changes

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#115]
Admin Dashboard to have : 
1.Number of Books/ LIC kit info against each donor to know the number of books they are raising funds for.
2.An EDIT button against each campaign for modifying campaigns if required.

**Comment by kuchlous** [comment]
Added the info in point 1 in the campaigns sheet but not on dashboard. The table is becoming too wide.
Edit button will take more work. Will file a separate bug for that.
