### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by purvishah77** [PrathamBooks/frp#125]
Status approved is confusing for browsers. Forget what the use case for this is. @kuchlous not sure whether to label this bug or enhancement. pl do decide.

If the workflow is inactive, expired and flagged benef are not being seen then this is not required.

If in the above scenarios the tiles will be seen then at least for active ones can we hide the same?

![status](https://cloud.githubusercontent.com/assets/10954914/8048794/875f0d62-0e73-11e5-811f-16f6b47afa15.png)

**Comment by kuchlous** [comment]
Agreed. Approved used to be 'Active'. I can change back to that.

If we should status on the non 'active' ones and not on active, it will be confusing. Ideas..

**Comment by purvishah77** [comment]
If status needs to be shown for all campaigns then Active is better

**Comment by kuchlous** [comment]
OK, Will make it Active.
