### ISSUE TITLE
sorting acting odd

### ISSUE THREAD

**Issue by purvishah77** [PrathamBooks/frp#126]
User selects eng language ( screenshot 1)
2 campaigns pop-up

Then users filters via featured ( screenshot 2)
IMO featured is a sub-set / sorting criteria within the above search parameters but i got 3 campaigns.

Not sure what the backend logic is.

![eng](https://cloud.githubusercontent.com/assets/10954914/8048900/d2e1d76e-0e74-11e5-9ae7-896d8174039b.png)

![sorting logic](https://cloud.githubusercontent.com/assets/10954914/8048902/ddb427e6-0e74-11e5-8ac7-e666cbb19c4c.png)

**Comment by kuchlous** [comment]
Seems to be a bug. Will fix.
