### ISSUE TITLE
Clear sort

### ISSUE THREAD

**Issue by purvishah77** [PrathamBooks/frp#127]
No way to un-select sorting criteria since its radio buttons. 

Need to add Clear sort.

This does not affect the other parameters since
a] they are check boxes
b] we have dynamic showcase as soon as user checks a box

![clear sort](https://cloud.githubusercontent.com/assets/10954914/8048925/346de4aa-0e75-11e5-9d8a-9e4b4174c046.png)

**Comment by kuchlous** [comment]
Clear sort is not needed as the campaigns are going to be sorted on one
thing or another.

**Comment by purvishah77** [comment]
in Which case then when a donor comes first to this page, something should be pre-selected, right?

![sorting3](https://cloud.githubusercontent.com/assets/10954914/8049139/834f6690-0e78-11e5-96b6-2021ceee4f17.png)

**Comment by kuchlous** [comment]
Yes. That makes sense. Maybe featured?

**Comment by purvishah77** [comment]
@Payoshni featured or recently launched.....whichever u guys feel will be more updated so that there is newness.

isn't featured already there on the homepage also?

**Comment by purvishah77** [comment]
ending soon could also be good. a lost push to campaigns

**Comment by Payoshni** [comment]
I feel Recently launched and ending soon both need to be given a push. @kuchlous  can we have both or any one? If one, maybe recently launched brings in more freshness
