### ISSUE TITLE
Gap between title and chlildren impacted

### ISSUE THREAD

**Issue by purvishah77** [PrathamBooks/frp#128]
Since the tiles layout used is pintrest type i am unsure why there is gap between title and children impacted.

Even if the title is long or short the text should seamlessly flow as the tiles can expand.

![spacing issue title to details](https://cloud.githubusercontent.com/assets/10954914/8048956/cc4cf4fa-0e75-11e5-8cf4-2bc2293c2b74.png)

**Comment by kuchlous** [comment]
They should all appear the same size and in fact they do on my browser. Will ask KLOC to take a look.

**Comment by kuchlous** [comment]
Sandeep, can you please check on firefox.

**Comment by pvsandeep** [comment]
Actually we have given minimum height 57px for 3 line title. It is taking 4
line for title.

update line no: 10255

#internalCampaign #campaigns .col-md-3 h2 {
    min-height: 80px;
}

On Wed, Jun 10, 2015 at 12:54 PM, AK <notifications@github.com> wrote:

> Sandeep, can you please check on firefox.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/128#issuecomment-110629539>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
Hmm!! This will cause even more gap between the title and rest of the fields in the other cards. BTW, this fits in 3 lines on my display. Could we make this resolution specific?

The max number of words in title are 10.

**Comment by pvsandeep** [comment]
Update the css code


@media (min-width: 992px) and (max-width: 1024px) {
  #internalCampaign .col-md-3 h2 {
    font-size: 1.5em;
    line-height: 1.3em;
    width: 95%;
}
}

On Wed, Jun 10, 2015 at 2:02 PM, AK <notifications@github.com> wrote:

> Hmm!! This will cause even more gap between the title and rest of the
> fields in the other cards. BTW, this fits in 3 lines on my display. Could
> we make this resolution specific?
>
> The max number of words in title are 10.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/128#issuecomment-110651174>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
@Payoshni please verify that the campaign cards are coming same size on your machine.

**Comment by Payoshni** [comment]
Same size on the homepage:

[image: Inline images 1]

same size on Donate page too:

[image: Inline images 2]

Regards,
Payoshni

“Someone reading a Book is a sign of order in the world”

-Mary Ruefle
