### ISSUE TITLE
change criteria error msg

### ISSUE THREAD

**Issue by purvishah77** [PrathamBooks/frp#130]
There are no campaigns that match your search criteria. Please try again.

Msg change to
There are no campaigns that match your search criteria. But we do have many many campaigns that need your help. Please refine your search or look at our Featured campaigns, handpicked just for you.

@Payoshni pl see if u want to alter the msg.

![criteria](https://cloud.githubusercontent.com/assets/10954914/8049021/b09841fa-0e76-11e5-90ac-2c9f28d4596b.png)

**Comment by Payoshni** [comment]
slight modification to this message. Let's use this @kuchlous -

Sorry! There are no campaigns that match your search criteria currently. You can modify your search or have a look at our handpicked *Featured campaigns list.

(can this link to the featured search criteria?)

**Comment by kuchlous** [comment]
OK.
