### ISSUE TITLE
search issue

### ISSUE THREAD

**Issue by purvishah77** [PrathamBooks/frp#131]
Kananda and Andra pradesh chosen.

Got 3 campaigns, not all had the above criteria. Not sure if the search happens also under synopsis of campaign.

![search issue](https://cloud.githubusercontent.com/assets/10954914/8049039/ed9b304e-0e76-11e5-9548-564abeb31499.png)

**Comment by kuchlous** [comment]
You should have got an error/warning when you chose these two as there are no campaigns that match. We show all campaigns in that case. We cal also clear the search radio buttons if that makes more sense.
