### ISSUE TITLE
sorting, search issue

### ISSUE THREAD

**Issue by purvishah77** [PrathamBooks/frp#132]
chose all for languages, and recently launched gave error msg.

![search 2](https://cloud.githubusercontent.com/assets/10954914/8049059/4b0a170e-0e77-11e5-92aa-5689e81cc2fd.png)

**Comment by kuchlous** [comment]
You probably have 'Andhra Pradesh' still chosen in states. Can you check again..

**Comment by purvishah77** [comment]
Re-checked the issue: had also ticked Andra pradesh. That is when the error msg came. if i unselected andra it gave me 3 campaigns showcased above. Which also seems odd. Since recently launched is all campaigns but in descending order of campaign launched date.

**Comment by purvishah77** [comment]
@kuchlous ha ha ...was already re-checking and just saw yr msg :)

**Comment by kuchlous** [comment]
As you mentioned earlier, sort criteria still respect the filters.

**Comment by kuchlous** [comment]
But point taken, on no campaigns found, will reset the filters.

**Comment by purvishah77** [comment]
Great. idea is to show more then less :)
