### ISSUE TITLE
pincode

### ISSUE THREAD

**Issue by purvishah77** [PrathamBooks/frp#133]
Pincode not pin....pin sounds like debit card pin

![pincode](https://cloud.githubusercontent.com/assets/10954914/8049114/0785642e-0e78-11e5-81e8-477947e352be.png)

**Comment by purvishah77** [comment]
@kuchlous  just for my learning will this qualify as bug or enhancement.

**Comment by kuchlous** [comment]
Bug is fine. Enhancement better left for new functionality.
