### ISSUE TITLE
Donor form Rs and books

### ISSUE THREAD

**Issue by purvishah77** [PrathamBooks/frp#135]
@Payoshni 
We had discussed this at some point. Was there a reason why this was skipped / removed.

Rs. 1000 ( xx books)

![rs to books](https://cloud.githubusercontent.com/assets/10954914/8049271/ae4fd2ec-0e7a-11e5-919a-39fe0dac37c7.png)

**Comment by kuchlous** [comment]
This line itself was not in the original spec. I added it. I will add the
books as well.

**Comment by Payoshni** [comment]
True. We had it in one of the versions and then it just dropped off. Thanks @kuchlous  for adding it.
It will mean: (have rounded it off)

Rs.1000 ( 28 books)
Rs.500 (14 books)
Rs.250 ( 7 books)
