### ISSUE TITLE
Donor form - Identification

### ISSUE THREAD

**Issue by purvishah77** [PrathamBooks/frp#136]
@Payoshni We had a explanation for the donor on why we ask this otherwise its a put-off. pl include the same.

![indetification](https://cloud.githubusercontent.com/assets/10954914/8049281/dee27ebe-0e7a-11e5-8375-ac1c86404f64.png)

**Comment by kuchlous** [comment]
Payoshni, please provide the explanation.

**Comment by kuchlous** [comment]
Need the wording so assigned to Payoshni.

**Comment by Payoshni** [comment]
Please put this below the Identification word with the font we are using for comments/tips/ smaller, in orange etc

This information is collected only for internal audit purpose as subject to the terms & conditions under our Privacy Policy.

the PP words can be linked? if yes, here : http://www.donateabook.org.in/about

@purvishah77  ran this line through Priyale for a legal opinion too.
