### ISSUE TITLE
Make the heading Sentence Case in Terms of Use under ABOUT

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#142]
e.g: Use of the Website/Eligibility

![image](https://cloud.githubusercontent.com/assets/12147445/8054033/2cc83104-0eb3-11e5-82d8-07d8ade23f48.png)

**Comment by kuchlous** [comment]
Did not understand. What do you want to replace with what?

**Comment by Payoshni** [comment]
all the heading become sentence case (they are all in all Caps right now)

This suggestion came from Suzie. They are following the same pattern for SW. For us this means that for the headings here, we will have to retype them to make them a sentence case from Upper case.

**Comment by kuchlous** [comment]
Sentence Case means first letter caps and then everything small. Right?

So PROHIBIHITED CAMPAIGNS becomes
Prohibihited campaigns

**Comment by Payoshni** [comment]
yes :)

Prohibited Campaigns

Regards,
Payoshni

“Someone reading a Book is a sign of order in the world”

-Mary Ruefle
