### ISSUE TITLE
Add webpage/blog/FB links to campaign page

### ISSUE THREAD

**Issue by kuchlous** [PrathamBooks/frp#158]

**Comment by Payoshni** [comment]
hi @kuchlous, is this linked? Because cannot see links.

**Comment by kuchlous** [comment]
No, it is not. I did not get css from the designer. Is this a show stopper?

**Comment by Payoshni** [comment]
It's important. By when are we expecting it?

**Comment by kuchlous** [comment]
Will ping the designer. He was busy with the responsive part.

**Comment by kuchlous** [comment]
@pvsandeep blog link is still missing. Added fb and webpage.

**Comment by pvsandeep** [comment]
*Html Code*

<li><i class="blog"></i><span>Blog:</span>
      <a href="https://donateabook.org.in/blog">www.donateabook.org.in/blog
</a>
    </li>

*Css code*

i.blog {
    background-position: -124px 9px;
}

[image: Inline image 2]

On Wed, Jun 24, 2015 at 7:58 PM, AK <notifications@github.com> wrote:

> @pvsandeep <https://github.com/pvsandeep> blog link is still missing.
> Added fb and webpage.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/158#issuecomment-114886678>.
>



-- 
Thanks,
Sandeep

**Comment by pvsandeep** [comment]
![campaigninfo-icons](https://cloud.githubusercontent.com/assets/11781550/8347671/57b6de54-1b26-11e5-9e91-8945466cac1e.png)
