### ISSUE TITLE
Change the DAB logo

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#161]
DAB logo to be updated. Jpeg and EPS sent on email

![image](https://cloud.githubusercontent.com/assets/12147445/8157174/1d4e034a-1370-11e5-8b7c-fcf8058a6c92.png)

**Comment by Payoshni** [comment]
Has this chnaged @kuchlous ? I can still see the old one.

**Comment by kuchlous** [comment]
Reload your page.

**Comment by Payoshni** [comment]
Cleared cache, cleared cookies, reloaded, still cannot see. You deployed this logo right?
![pratham book logo with tag-01 1](https://cloud.githubusercontent.com/assets/12147445/8177279/b6d7d616-1420-11e5-8e07-f29b40c9e978.jpg)
