### ISSUE TITLE
Add the Organisation's name in the admin dashboard

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#162]
Just having the Title of the campaign is very confusing for the Admin as it is mostly not representative/connected to the Beneficiary Org. Adding that  in the admin dashboard allows for quick edits/updated etc.

![image](https://cloud.githubusercontent.com/assets/12147445/8157236/b3a32064-1370-11e5-809a-f1a56f9e99e8.png)

**Comment by kuchlous** [comment]
Should I remove the Type. The table will become too large otherwise..

**Comment by Payoshni** [comment]
Yes. Can remove Type.
