### ISSUE TITLE
FB share not allowed for Campaigns: Shows error msg

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#163]
When trying to share campaign on FB using the share button - getting the following message : "Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains."

![image](https://cloud.githubusercontent.com/assets/12147445/8157294/50902a0c-1371-11e5-922a-4aa7f2df304e.png)

**Comment by kuchlous** [comment]
Just tried. It works fine for me. Please try again. If it still does not work, please copy provide the address from the facebook window.

![screen shot 2015-06-15 at 3 46 31 pm](https://cloud.githubusercontent.com/assets/1202539/8157892/e38704a8-1375-11e5-960d-0dc8b4c1ea78.png)

**Comment by kuchlous** [comment]
I am closing this. Please reopen if it is still a problem.
