### ISSUE TITLE
Changing the message on Twitter share

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#164]
Twitter share message to be changed: To include hashtag #donateabook automatically and Tag @prathambooks in place of the name. Final message to be:

I am helping India's children read.Donate books on @prathambooks 's Donate-a-Book. #donateabook

![image](https://cloud.githubusercontent.com/assets/12147445/8157335/a62194f6-1371-11e5-8b99-ab8253c9c661.png)

**Comment by Payoshni** [comment]
Can the message/code pick up remaining amount like how Rangde does?

![image](https://cloud.githubusercontent.com/assets/12147445/8157725/7cae1204-1374-11e5-8d71-8a5a45a42eb9.png)

**Comment by kuchlous** [comment]
Yes. It can. Send me the final message.

**Comment by kuchlous** [comment]
rangde does not seem to be picking the amount directly. Seems that the user added the message by hand but we could pick it.

**Comment by kuchlous** [comment]
Changed the message. If you want amount etc. please reopen with exact message.

**Comment by Payoshni** [comment]
No, this is fine. I was rethinking and it just doesn't make sense for us to include amount till we know exactly how people are using it/sharing it. So best to play safe. This is closed then. Thanks
