### ISSUE TITLE
New text and link for the Success Stories at the bottom

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#174]
Samiksha Foundation Creative Learning Initiative for children with cancer and their caregivers. They have setup a library at the hospital for these children and the teachers/volunteers help cataloging ,maintaining the library,help children read books. Older children also get to borrow books ,read them on their own/with parent and return them to the library.
The children are hospital bound with limited activities.They miss school, learning , fun and games that comes with a normal childhood. Samiksha fills this gap and brings education and fun to the children (at the hospital) while they are being treated at the hospital. This way the children will be able to be in touch with reading/writing ,academics and can go back to school with less/no difficulty.

Link this to: http://blog.prathambooks.org/2014/03/notes-from-field-samiksha-foundation.html

![image](https://cloud.githubusercontent.com/assets/12147445/8158890/19928e42-137f-11e5-8aea-5ad1e08b61a7.png)

**Comment by kuchlous** [comment]
I have updated it but it does not read very well. Please check with a
copywriter.
