### ISSUE TITLE
Under SET UP: a separate tab for Social Media Handbook

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#186]
We have created a SociaL Media Handbook for beneficiaries on ways to use Social Media. It would be great to also add it in SET UP so that people can have a look at it while setting up their campaigns.

It's a pdf so can send on email if doable.

**Comment by kuchlous** [comment]
Send it across. Also ideas on where to put the link and the copy to go
along with it.

**Comment by kuchlous** [comment]
Payoshni, We have added this. Please review. Also, where do you want the
pdf to go? Copy?

**Comment by Payoshni** [comment]
@kuchlous

Looks good. In the email have sent a pdf, which need to be attached to this line:

Click here to download the handbook.

(This line will come right at the bottom of the page. please underline Click here)

**Comment by Payoshni** [comment]
have sent fresh email with the pdf with updated logo. Please use that.
