### ISSUE TITLE
DAB logo on the website to be updated

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#191]
Logo on website to be updated.
The colour of the dash has changed and the vision statement is in lower case.
![dab final logo](https://cloud.githubusercontent.com/assets/12147445/8281955/8c63f0c4-190a-11e5-838f-f9d59e44ad8b.png)

**Comment by pvsandeep** [comment]
I need fonts used for logo. If I reduce the logo size letters are showing
in blur.

On Mon, Jun 22, 2015 at 7:32 PM, AK <notifications@github.com> wrote:

> Assigned #191 <https://github.com/PrathamBooks/frp/issues/191> to
> @pvsandeep <https://github.com/pvsandeep>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/191#event-336730512>.
>



-- 
Thanks,
Sandeep

**Comment by Payoshni** [comment]
@pvsandeep @kuchlous
these are the font names. Do you need the font files?

Pratham Books:
Font Name- Gill Sans MT Regular
Donate a Book:
Font Name- Gill Sans MT Bold
Help India's Children Read:
Font Name- Humanst521 Lt BT Light

**Comment by pvsandeep** [comment]
Update the logo images.

On Tue, Jun 23, 2015 at 3:32 PM, Payoshni <notifications@github.com> wrote:

> @pvsandeep <https://github.com/pvsandeep> @kuchlous
> <https://github.com/kuchlous>
> these are the font names. Do you need the font files?
>
> Pratham Books:
> Font Name- Gill Sans MT Regular
> Donate a Book:
> Font Name- Gill Sans MT Bold
> Help India's Children Read:
> Font Name- Humanst521 Lt BT Light
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/191#issuecomment-114428060>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
@pvsandeep , where are the images?

**Comment by pvsandeep** [comment]
![pratham_logo](https://cloud.githubusercontent.com/assets/11781550/8305750/a67ed63e-19cf-11e5-8202-cb8e40ca9acc.png)
![caption](https://cloud.githubusercontent.com/assets/11781550/8305751/a683106e-19cf-11e5-8e5b-9a41f670a995.png)
