### ISSUE TITLE
Transaction sucessful but bad request info

### ISSUE THREAD

**Issue by purvishah77** [PrathamBooks/frp#192]
Transaction successful got email from CC avenues but following 2 messages came

This one is not re-assuring :(. but clicked yes
![screenshot from 2015-06-22 18 18 35](https://cloud.githubusercontent.com/assets/10954914/8282052/663623d0-190b-11e5-9c51-f8563a46b566.png)

Then this one came
![screenshot from 2015-06-22 18 18 52](https://cloud.githubusercontent.com/assets/10954914/8282058/6d90bb68-190b-11e5-953f-e74729adcc33.png)

Email from CC avenues
![screenshot from 2015-06-22 18 21 14](https://cloud.githubusercontent.com/assets/10954914/8282069/8194a2f0-190b-11e5-894e-98aedeae7bbb.png)

**Comment by kuchlous** [comment]
Try now. I fixed it and just made a donation. It was due to our moving to https.

**Comment by purvishah77** [comment]
@kuchlous credit card has been swiped. Have got msg also. should i make one more donation?

**Comment by kuchlous** [comment]
Did not understand. Did you reach the thank-you page on d-a-b? Did you get
a thank you email? Did your donation show up on the site?

**Comment by kuchlous** [comment]
Your donation still did not make it to the site..
