### ISSUE TITLE
Stats not updated

### ISSUE THREAD

**Issue by purvishah77** [PrathamBooks/frp#193]
Not sure if this is linked to issue191 maybe the system has not got the data back from CC avenues but

book count on home page has not increased and benef page also not showing books donated.

![books not changed](https://cloud.githubusercontent.com/assets/10954914/8282257/d561eba8-190c-11e5-9848-715e93e8dc7c.png)

![donation](https://cloud.githubusercontent.com/assets/10954914/8282269/e4bc328e-190c-11e5-83ff-a7f0fefeb405.png)

**Comment by kuchlous** [comment]
Same as #192
