### ISSUE TITLE
Campaign dates to be reset tomrrow for the launch

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#195]
@kuchlous 
All campaigns to be reset to start tomorrow: 24-06-15 and run for 30 days thereon.

**Comment by kuchlous** [comment]
@Payoshni , you can do this yourself. Just change the status of the campaign to 'Waiting Approval' and back to 'Approved'. It will reset the time.

**Comment by kuchlous** [comment]
@Payoshni , I reset them because if you had done it, mails would have gone to the campaign owners again. If you do want mails to go to them , go through the process mentioned above.

**Comment by Payoshni** [comment]
thanks @kuchlous
