### ISSUE TITLE
Creating a new static page for Donate-a-thon

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#197]
A new statisc page to be created under ABOUT: https://donateabook.org.in/about

After About Pratham Books and before FAQs: this text to go on the page-

Heading: 50,000 books.  1,00,000 children. A nation of little readers! 
Body Text:  Pratham Books launches a Donate-a-thon to get India's children to read. By Children's Day we hope to ship 50,000 books to children across India.

The platform has many beneficiaries that have put in their book requests and donors, such as you can help us get books to them. From Puducherry to Ladakh, from Odisha to Rajasthan,from Tamil Nadu to Thane, children await books in English, Hindi, Telugu, Marathi and many other Indian languages. A sum as small as Rs.500/- can help donate 15 books. Every rupee donated on this platform goes towards the books, and ensuring they reach the children for whom they are meant.

Click here to browse through our featured campaigns.

**Comment by kuchlous** [comment]
@RCReddy , this is urgent. Need by tomorrow.

**Comment by purvishah77** [comment]
@Payoshni pl send edm out after this page is up.
