### ISSUE TITLE
Adding a new banner for Donate-a-thon

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#198]
I will share in an hour's time. To be added in the carousel on the top of the website

**Comment by Payoshni** [comment]
banner image sent on email.
![donate-a-book banner for the web 230615 1](https://cloud.githubusercontent.com/assets/12147445/8305753/ac4951de-19cf-11e5-9c97-977215305cda.jpg)

**Comment by kuchlous** [comment]
Note that the text on this says "Read more" while other say "Click to know more". All 3 of them link to "How it works".

**Comment by purvishah77** [comment]
@kuchlous @RCReddy  it needs to go to the page references in issue 197.
