### ISSUE TITLE
odd american express issue

### ISSUE THREAD

**Issue by purvishah77** [PrathamBooks/frp#199]
all sites where i buy online i need to put the one time password EVERYTIME i make  a purchase.

weirdly today when i used the same card on DAB it did not ask for the same. Had used it yesterday as well on DAB.

Bit unnerving @kuchlous hope the system is not saving any data that it should not be.

**Comment by kuchlous** [comment]
No, we are not saving any data. The payment processing is completely with
ccavenue.
