### ISSUE TITLE
Right link disabled

### ISSUE THREAD

**Issue by purvishah77** [PrathamBooks/frp#204]
Right link on campaign tile is disabled.

Use case: Sorted beneficiaries and got about 8 options. The hover info itself is not enough to make a decision so want to read more. Logical next step is to open the shortlisted campaign in  a new tab so that my original filtering stays.

![right link](https://cloud.githubusercontent.com/assets/10954914/8311537/69fb5b72-19f4-11e5-8c08-22ec93872720.png)

**Comment by kuchlous** [comment]
Click now opens a new tab. Closing.
