### ISSUE TITLE
User feedback : panels moving too fast

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#208]
1.The panels for each of the organisations - move way too rapidly. - they are obviously set for a fast auto play. and its too fast to be able to read through what the organisation is about or who the books are for,.

2.Once I press donate - and then click on any of the 3 options ( rs 1000, 500 ..) and then go to the customize your donation to add an amount , i am not able to .  i have go back a webpage and start the process all over again

**Comment by kuchlous** [comment]
Filing separate bug for the donate problem.
