### ISSUE TITLE
odd spacing

### ISSUE THREAD

**Issue by purvishah77** [PrathamBooks/frp#209]
Odd spacing between campaigns. There are 2 more in third row but second row is empty

![odd spacing](https://cloud.githubusercontent.com/assets/10954914/8331004/29482b0a-1aa3-11e5-86a8-2674985cc1bc.png)

**Comment by pvsandeep** [comment]
Update line no: 9000

#internalCampaign #campaigns .col-md-3 h2 {
*  min-height: 60px;*
}

Update line no: 8972


span.featured-campaign {
  background-image: url("../images/featured-champion.png");
  background-position: right 5px;
  background-repeat: no-repeat;
  background-size: 41px auto;
  color: #222222;
  float: right;
  font-size: 8px;
  margin: -25px -12px -20px 0;
 * padding: 28px 0 5px;*
  position: relative;
  right: 0;
  text-transform: uppercase;
  width: 78px;
}

On Wed, Jun 24, 2015 at 7:01 PM, AK <notifications@github.com> wrote:

> Assigned #209 <https://github.com/PrathamBooks/frp/issues/209> to
> @pvsandeep <https://github.com/pvsandeep>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/209#event-338935308>.
>



-- 
Thanks,
Sandeep
