### ISSUE TITLE
User Feedback - Donate page custom amount should override the radio button

### ISSUE THREAD

**Issue by kuchlous** [PrathamBooks/frp#212]
Once I press donate - and then click on any of the 3 options ( rs 1000, 500 ..) and then go to the customize your donation to add an amount , i am not able to . i have go back a webpage and start the process all over again

**Comment by Payoshni** [comment]
@RCReddy Can you please take this on priority? getting messages on Social Media because people are not able to customise amounts and holding on to paymnets hence.
