### ISSUE TITLE
Carousel with featured campaigns to have a 'Click here to see more campaigns' on top'

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#216]
Many users were surprised to know we have many campaigns, The general feel because of the carousel, is that there are only 6 campaigns.
Can we put a line right on top saying  'Click here to see more campaigns' (on right hand side of the carousel)

![image](https://cloud.githubusercontent.com/assets/12147445/8347936/51a37190-1b2a-11e5-897d-879ce99e221f.png)

**Comment by kuchlous** [comment]
For css, assigned to Sandeep at KLOC.

**Comment by pvsandeep** [comment]
*Html Code*

<div class="col-md-12">
  <h2>What's a world without books?</h2>
  <p> We hope children will never know.
    <a href="/donate">Join us</a>
    in a mission to help India's
    children read. </p>
 * <p class="see-more">*
*    <a href="/donate">Click here to see more campaigns</a>*
*  </p>*
</div>



*Css Code*

.tab-content .col-md-12 p.see-more {
  float: right;
  font-size: 14px;
margin-right: 10px;
}

@media (max-width: 767px)
.tab-content .col-md-12 p.see-more {
  float: initial !important;
  text-align: center;
margin-right: 0 !important;
}


[image: Inline image 1]

On Thu, Jun 25, 2015 at 11:53 AM, AK <notifications@github.com> wrote:

> For css, assigned to Sandeep at KLOC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/216#issuecomment-115121804>.
>



-- 
Thanks,
Sandeep
