### ISSUE TITLE
Donation page does not inherit street  address, State and ID type from profile page. 

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#223]
Donation page Does not inherit street  address, State and ID type from profile page. Need to re-enter it.

![image](https://cloud.githubusercontent.com/assets/12147445/8370866/18f5e338-1bec-11e5-9dda-8e29f412fe0b.png)

**Comment by kuchlous** [comment]
I thought I had taken care of this. Will take a look.

**Comment by kuchlous** [comment]
Fixed.
