### ISSUE TITLE
Communication of a fully funded campaign on DAB

### ISSUE THREAD

**Issue by purvishah77** [PrathamBooks/frp#227]
Is there an icon for fully funded? we should have one and grey the campaign out.
Also even after a month would ended campaigns come up in searches?
Also it should say somewhere closed campaign otherwise looks still open for funding

![Uploading fully funded2.png…]()
![Uploading full funded.png…]()

**Comment by purvishah77** [comment]
Sorry in a meeting and net is very flaky here. icon is looking the same as featured. greying out tile will help.

**Comment by kuchlous** [comment]
I think it will come only when it is active - less than 30 days and admin
has not closed it.

**Comment by kuchlous** [comment]
You mean grey out the title of the campaign. I also want to change the
'Donate button'.

**Comment by purvishah77** [comment]
Yes grey the same out.

**Comment by kuchlous** [comment]
Greyed..
