### ISSUE TITLE
No way for admin to know the progress of campaigns through the dashboard

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#231]
Can a % ticker of how campaign is doing be on the admin dashboard. For the last 4 campaigns that went fully funded, I had to go to the donate  page and search which ones got fully funded.

**Comment by purvishah77** [comment]
There are filters for campaigns right? can one be full funded on the admin page?

**Comment by Payoshni** [comment]
no filters as of now @purvishah77

**Comment by kuchlous** [comment]
@sandeepgoud , for now add a new column with percentage funded.
