### ISSUE TITLE
100% fully funded emails not going

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#233]
@kuchlous 

The 100%, fully funded campaign emails are probably not going to the beneficiaries. Another one wrote to me worried as he saw the campaign is closed but didn't understand that it's been fully funded. Can you please check? I will also ask him to recheck once again.

**Comment by kuchlous** [comment]
I checked but did not find any issues so far. Can you ask them to check in their spam folders as well?

**Comment by Payoshni** [comment]
okay, i will check and get back.

**Comment by kuchlous** [comment]
There was a bug in the code. Fixed it now. Please check next time..
