### ISSUE TITLE
Donations report from admin dashbaord

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#234]
Can we please have these 3 things added urgently in the Donations dashboard?

Donor's address
Donor's id card (which he used)
Donor's Id card number

This is required for 80G certifications, hence requested urgently.
Thanks.

**Comment by kuchlous** [comment]
Note that we are not preserving the donor address, that is taken only for ccavenue purposes. We only keep the donor city, state and pin in our db's. We can add the address also, but it is not there right now. Originally the idea was that accounts will email the person to get their address.

**Comment by Payoshni** [comment]
@kuchlous Maybe that time, but our learning is evolving each day. Let's please capture all the 3 i have mentioned.

**Comment by kuchlous** [comment]
Ok. Will take a bit of time.

**Comment by kuchlous** [comment]
Added city, state, type and id number. Need db changes for address so it will take some time.

**Comment by Payoshni** [comment]
thanks @kuchlous. For my immediate problem today, this is okay but need the address for 80G,whenever you get time. (need it by 15th July if possible)

**Comment by kuchlous** [comment]
Added to the db and henceforth will save in db. For older donations will send to you.

Assigning to @sandeepgoud to add this to donations XL sheet.

**Comment by Payoshni** [comment]
@kuchlous  added address right? Thanks. Will wait for it to come to XL too .

**Comment by kuchlous** [comment]
Yes. Two step process. For new donations you will addresses automatically.
For older donations, we need to populate database from some other data.
Will take a couple of days.

**Comment by kuchlous** [comment]
Fixed..
