### ISSUE TITLE
Facebook share says Pratham, in place of Pratham Books

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#238]
To say Pratham Books' Donate-a-Book

(books is missing currently which makes it an incorrect organisation name)

![image](https://cloud.githubusercontent.com/assets/12147445/8453968/3d1fdea6-2017-11e5-904d-7f6a14ca9527.png)

**Comment by kuchlous** [comment]
Fixed but will take some time before it starts showing up.
