### ISSUE TITLE
Donation page: Only PanCard option to be kept and to be made mandatory

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#242]
as discussed with @kuchlous 

On the Donation page, remove all other ID Cards .  Remove Identification and the line underneath it.
Just have Pan Card in the box on left, and space for the number on box on the right.

This line to be put under the boxes.
This information is mandatory as per Government guidelines. We solicit your cooperation.

**Comment by Payoshni** [comment]
@kuchlous  @RCReddy  Can this be closed urgently today please? Getting too many high risk transactions and need PAN to validate all those.

**Comment by kuchlous** [comment]
Yes, today.
