### ISSUE TITLE
Button for Similar Campaigns in fully funded pop up not correct

### ISSUE THREAD

**Issue by kuchlous** [PrathamBooks/frp#245]
Go to:

https://donateabook.org.in/campaign/35

click on "Donate to this campaign".

This is on chrome.

<img width="1280" alt="screen shot 2015-07-04 at 4 13 08 pm" src="https://cloud.githubusercontent.com/assets/1202539/8507591/beaaa404-2267-11e5-9cbe-7a5614687cef.png">

**Comment by purvishah77** [comment]
On ubuntu also similar issue. Also pop-pup should come up alongwith the campaign. I should not have to click on the donate button for the same.

Lastly some text changes. IMO @Payoshni pl take a look and revert to mirafra.
Heading should say:

Campaign closed

We are very thankful to donors such as you to help this campaign reach its funding goal. If you are looking to fund campaigns such as this one please click on the link below.

Donate to similar campaigns

**Comment by pvsandeep** [comment]
Replace html code.

<div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        <h3 class="modal-title" id="myLargeModalLabel">Campaign closed</h3>
      </div>
      <div class="row">
        <div class="col-xs-12">
 <h4>We are very thankful to donors such as you to help this campaign reach its funding goal. If you are looking to fund campaigns such as this one please click on the link below.</h4>
        </div>
        <a type="button" href="/donate"><button class="btn browse-btn pull-right">Donate to similar campaigns</button></a>
      </div>
    </div>

![screenshot](https://cloud.githubusercontent.com/assets/11781550/8516086/190970b8-23cd-11e5-8524-6ada74790e49.jpg)

**Comment by pvsandeep** [comment]
Replace html code.


<div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span
aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        <h3 class="modal-title" id="myLargeModalLabel">Campaign closed</h3>
      </div>
      <div class="row">
        <div class="col-xs-12">
 <h4>We are very thankful to donors such as you to help this campaign reach
its funding goal. If you are looking to fund campaigns such as this one
please click on the link below.</h4>
        </div>
        <a type="button" href="/donate"><button class="btn browse-btn
pull-right">Donate to similar campaigns</button></a>
      </div>
    </div>

On Sun, Jul 5, 2015 at 10:17 AM, purvishah77 <notifications@github.com>
wrote:

> On ubuntu also similar issue. Also pop-pup should come up alongwith the
> campaign. I should not have to click on the donate button for the same.
>
> Lastly some text changes. IMO @Payoshni <https://github.com/Payoshni> pl
> take a look and revert to mirafra.
> Heading should say:
>
> Campaign closed
>
> We are very thankful to donors such as you to help this campaign reach its
> funding goal. If you are looking to fund campaigns such as this one please
> click on the link below.
>
> Donate to similar campaigns
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/245#issuecomment-118579490>.
>



-- 
Thanks,
Sandeep

**Comment by RCReddy** [comment]
@pvsandeep can you please send the css for button.

**Comment by pvsandeep** [comment]
Css is already in  prathambooks.css

Just remove "*btn pull-right*" class in a tag (anchor tag) and put this
class name in button "*btn browse-btn pull-righ*t".

<a type="button" href="/donate"><button class="*btn browse-btn
pull-right*">Donate
to similar campaigns</button></a>

On Mon, Jul 6, 2015 at 3:30 PM, RCReddy Murikinati <notifications@github.com
> wrote:

> @pvsandeep <https://github.com/pvsandeep> can you please send the css for
> button.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/245#issuecomment-118792107>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
@Payoshni @purvishah77 , button is fixed but the English feels a little clunky (repetition of such as). Please check..

**Comment by purvishah77** [comment]
@Payoshni new assignment for piyali :)

**Comment by Payoshni** [comment]
@purvishah77  this was closed yesterday before I could react :)

@kuchlous 
Language edit as this: 
We are thankful to donors like you who helped this campaign reach its funding goal. You can help other campaigns similar to this one! Please click on the link below.
