### ISSUE TITLE
Home page layout problem on screen size 1920x1080

### ISSUE THREAD

**Issue by kuchlous** [PrathamBooks/frp#246]
Look at the login/signup, overlaps with logo.

![screenshot](https://cloud.githubusercontent.com/assets/1202539/8510588/ffd81950-230e-11e5-980b-97cf79db0281.png)

**Comment by pvsandeep** [comment]
Update css code in line no: 7510
    
header #login {
    left: 38%;
    position: absolute;
    top: 56px;
}
