### ISSUE TITLE
Issue with full fudded donate button.

### ISSUE THREAD

**Issue by RCReddy** [PrathamBooks/frp#248]
Go to:
https://donateabook.org.in/donate

##### Incorrect:
Click on "Donate" button of any fully fundded campaign. It will take you to donation form which is in correct.
##### Expected: 
Click on "Donate" button of any fully fundded campaign It should open pop-up like below.
![190970b8-23cd-11e5-8524-6ada74790e49](https://cloud.githubusercontent.com/assets/5663402/8520391/4c20b888-23f7-11e5-92c9-a87c36c3f0d4.jpg)

It would be greate to have different button color for fully fundded campaign.

**Comment by kuchlous** [comment]
Now we disable the donate btn and show a tooltip with a similar message.
