### ISSUE TITLE
Sort function for each column in the admin dashboard

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#254]
as previously requested. For each of the data column in the admin dashboard : to have a sort function to make sense of the data

**Comment by kuchlous** [comment]
It is there. Just not visible :) Just click on the title at the top of the
column.

**Comment by Payoshni** [comment]
aaah, my bad! thanks :)

**Comment by Payoshni** [comment]
aah, my bad. Thanks :)
