### ISSUE TITLE
Trying to add donation. Throws me this error

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#257]
![image](https://cloud.githubusercontent.com/assets/12147445/8670830/d698b6d6-2a3d-11e5-9ec6-987340de88ea.png)

**Comment by kuchlous** [comment]
Probably wrong email. Has she created an account? Else you have to do it.

**Comment by Payoshni** [comment]
she has created an account on an earlier occasion, hence not able to add
her again as a user.
Cannot ask her for login details, what can we do?



Regards,
Payoshni

“Someone reading a Book is a sign of order in the world”

-Mary Ruefle

**Comment by kuchlous** [comment]
I can see that she is there. Can you see if you put extra space or
something..

**Comment by kuchlous** [comment]
@Payoshni , is this solved?

**Comment by Payoshni** [comment]
yes it is. I tried after a while and it worked. Sorry, should have closed
it.

Regards,
Payoshni

“Someone reading a Book is a sign of order in the world”

-Mary Ruefle

**Comment by kuchlous** [comment]
Can you please close it now?
