### ISSUE TITLE
Donation emails: not all going

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#259]
A beneficiary commented saying she has 6 donors but received only 4 emails, which may mean some problem with the system for not sending every email?

![image](https://cloud.githubusercontent.com/assets/12147445/8741173/70a1eece-2c72-11e5-8a1a-285e06fe7b80.png)

**Comment by kuchlous** [comment]
Please ask her to check spam folder as well. Are the two missing emails for
anonymous donors?

**Comment by kuchlous** [comment]
@Payoshni , any feedback on this? Any one else reported any issues with receiving emails?

**Comment by Payoshni** [comment]
Nothing. No one else has reported too. Let's just check the codes once, and if all okay from our end, let's close as i dont have any other documentation on the same.

**Comment by kuchlous** [comment]
Already reviewed the code..
