### ISSUE TITLE
Featured and fully funded badges overlapping

### ISSUE THREAD

**Issue by kuchlous** [PrathamBooks/frp#260]
Go to:

https://donateabook.org.in/donate

Look for the campaign Pehchaan. 

<img width="1280" alt="screen shot 2015-07-18 at 11 56 01 am" src="https://cloud.githubusercontent.com/assets/1202539/8760595/222c0450-2d44-11e5-8ca3-ec2f5794689b.png">

**Comment by pvsandeep** [comment]
We need to add one div before span for all.

*<div class="campaigns-icons">*

<span class="champion">Fully<br> Funded</span>
<span class="featured-campaign">Featured</span>

*</div>*


I have updated CSS code in attached* prathambooks.css *

On Sat, Jul 18, 2015 at 11:57 AM, AK <notifications@github.com> wrote:

> Assigned #260 <https://github.com/PrathamBooks/frp/issues/260> to
> @pvsandeep <https://github.com/pvsandeep>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/260#event-359109631>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
@pvsandeep , need the css file. You can email it to me if unable to attach here.
