### ISSUE TITLE
another campaign goes over 100%

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#261]
https://donateabook.org.in/campaign/9

**Comment by kuchlous** [comment]
May be the last donation made was more than what was needed. Can you please
check?

**Comment by Payoshni** [comment]
yes, it was. It was 20k, which was more than what they needed.

Regards,
Payoshni

“Someone reading a Book is a sign of order in the world”

-Mary Ruefle

**Comment by kuchlous** [comment]
We do not block more than what is needed. I think that is OK. Else I will
have to generate errors on the donor page which is not a great use model.

**Comment by Payoshni** [comment]
No, perfect. even i think that's okay.
So ignore please. :)

i thought some other major bug.

Regards,
Payoshni

“Someone reading a Book is a sign of order in the world”

-Mary Ruefle

**Comment by kuchlous** [comment]
Please close in that case..
