### ISSUE TITLE
Campaigns to be extended for 10 days starting tomrrow

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#262]
Campaigns to be extended:

https://donateabook.org.in/campaign/33
https://donateabook.org.in/campaign/29
https://donateabook.org.in/campaign/26
https://donateabook.org.in/campaign/27
https://donateabook.org.in/campaign/24
https://donateabook.org.in/campaign/23
https://donateabook.org.in/campaign/22
https://donateabook.org.in/campaign/21
https://donateabook.org.in/campaign/18
https://donateabook.org.in/campaign/13
https://donateabook.org.in/campaign/12
https://donateabook.org.in/campaign/11
https://donateabook.org.in/campaign/6
https://donateabook.org.in/campaign/5
https://donateabook.org.in/campaign/4
https://donateabook.org.in/campaign/3
https://donateabook.org.in/campaign/1

**Comment by kuchlous** [comment]
Done. All of them now have 12 days left..
