### ISSUE TITLE
Sharing on Social Media for campaigns

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#264]
1.Make share buttons more prominent on campaign pages. Many supporters will not donate but are happy to share campaigns on Facebook.  

2. Add share buttons on post checkout conversation.  After someone donates,  they want to quickly tell their friends. Make it easy.

**Comment by kuchlous** [comment]
@pvsandeep , can you help with the styling for these?

**Comment by kuchlous** [comment]
@pvsandeep , for current page that the user reaches after completing a donation, either you can make a small donation on the site (even re 1 will go through) or I can give you the html for the page. We want share buttons prominently on that page.

**Comment by kuchlous** [comment]
@pvsandeep , please let me know if you will have time to work on this.

**Comment by pvsandeep** [comment]
Please send me the url link on which page you want me to style or send me
the html for that page.

Toady I am have other work to do so tomorrow I will work.

On Mon, Aug 17, 2015 at 1:05 PM, AK <notifications@github.com> wrote:

> @pvsandeep <https://github.com/pvsandeep> , please let me know if you
> will have time to work on this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/264#issuecomment-131706985>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
@pvsandeep 

For 1.

https://donateabook.org.in/campaign/48-Cultivate-reading-habit

Need to make the social icons bigger and more prominent.

For 2.

either you can make a small donation on the site (even re 1 will go through) or I can give you the html for the page. We want share buttons prominently on that page.

I would prefer you see the live page after making a small donation rather than me providing you with html.

**Comment by pvsandeep** [comment]
For 1

Please update css code and attached social icons.

*Update  CSS code:*

.socialIcons {
    float: left;
    margin: 0 auto !important;
    text-align: center;
    width: 100%;
}

.campaignTop span.tw {
    background-image: url("../images/tw-share.png");
    cursor: pointer;
    display: inline-block;
    float: initial;
    margin: 0;
}
.campaignTop span.tw:hover {
    background-image: url("../images/tw-share.png");
    opacity: .7;
}
.campaignTop span.fb {
    background-image: url("../images/fb-share.png");
    cursor: pointer;
    display: inline-block;
    float: initial;
}
.campaignTop span.fb:hover {
    background-image: url("../images/fb-share.png");
    opacity: .7;
}

On Mon, Aug 17, 2015 at 2:44 PM, AK <notifications@github.com> wrote:

> @pvsandeep <https://github.com/pvsandeep>
>
> For 1.
>
> https://donateabook.org.in/campaign/48-Cultivate-reading-habit
>
> Need to make the social icons bigger and more prominent.
>
> For 2.
>
> either you can make a small donation on the site (even re 1 will go
> through) or I can give you the html for the page. We want share buttons
> prominently on that page.
>
> I would prefer you see the live page after making a small donation rather
> than me providing you with html.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/264#issuecomment-131740179>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
@pvsandeep , can you please send me the social icons separately in an email. Did not get them here.

**Comment by kuchlous** [comment]
@pvsandeep , also if you can attach screen shots I will know how you expect the screens to look.

**Comment by kuchlous** [comment]
Deployed 1.

**Comment by kuchlous** [comment]
Fixed..
