### ISSUE TITLE
Change in APP name & Campaign name for SM

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#266]
-​The Facebook app name used to log in should always be the name of the org with the orgs logo. Right now,  there is no logo and the name is "frp" or something. Looks suspicious. 

-Url to have campaign name rather than number

**Comment by kuchlous** [comment]
Second part is done.

**Comment by kuchlous** [comment]
Facebook updated with donate-a-book name. Need logo in right size for uploading.

**Comment by kuchlous** [comment]
<img width="1280" alt="screen shot 2015-10-09 at 11 10 53 am" src="https://cloud.githubusercontent.com/assets/1202539/10386578/99cc0654-6e76-11e5-89ac-7a371fac2398.png">
