### ISSUE TITLE
Discrepancy in donation amount b/w Beneficiary Dashboard & Admin dashboard+campaign page

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#271]
For this campaign:
Our admin dashboard shows Donation amount to be INR 6450
Campaign page shows donation amount to be INR 6431
The Beneficiary's dashboard shows amount of INR 9581

Which one is correct and how do we resolve this? Please help. 

![image](https://cloud.githubusercontent.com/assets/12147445/9104557/9548edea-3c2b-11e5-94d7-f9a66c12f357.png)

![image](https://cloud.githubusercontent.com/assets/12147445/9104560/a8b50b7a-3c2b-11e5-82df-40ee337a7640.png)

![image](https://cloud.githubusercontent.com/assets/12147445/9104565/bed6c22c-3c2b-11e5-8592-101cfc2be9a5.png)

**Comment by kuchlous** [comment]
The beneficiary page is wrong. It included even those donations which did not go through ccav for different reasons. Will fix.

**Comment by kuchlous** [comment]
Fixed. Ask the beneficiary to try now..

**Comment by Payoshni** [comment]
So how much is the final donation amount for this campaign? The campiagn
sheet that we download is also incorrect then, no?

Regards,
Payoshni

“Someone reading a Book is a sign of order in the world”

-Mary Ruefle

**Comment by kuchlous** [comment]
No, the sheet is correct. The amount on the campaign page is the target but
they raised a few rupees more as the last donation may have been a little
bigger than needed.

**Comment by Payoshni** [comment]
My question is, what is the final donation amount for this campaign.Asking
because the beneficiary's donation page shows 9k while our sheet shows
6450. This is a big discrepancy!


Regards,
Payoshni

“Someone reading a Book is a sign of order in the world”

-Mary Ruefle

**Comment by kuchlous** [comment]
Now the beneficiary page will also show 6450.

**Comment by Payoshni** [comment]
So, her dashboard is incorrect? How do I explain this to her. Because on
her dashboard she sees a bigger amount.
Where has that money gone?


Regards,
Payoshni

“Someone reading a Book is a sign of order in the world”

-Mary Ruefle
