### ISSUE TITLE
url issue

### ISSUE THREAD

**Issue by purvishah77** [PrathamBooks/frp#272]
Even if i click on social media tab the url stays the same

https://donateabook.org.in/setup

It gets a little confusing when u want to direct people to a particular tab.

**Comment by Payoshni** [comment]
Yes, same problem with all other tabs too, especially in ABOUT when you want to guide people to a specific page , e.g Donate-a-thon write up or Social Media etc.

**Comment by kuchlous** [comment]
This was fixed recently.
