### ISSUE TITLE
Average book value to change to INR 40 per book 

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#276]
Existing books value : 36.75
To be changed to 40  per book

No other changes required in the LIC or Books tab
 @kuchlous  Can delete the 5k code then. INR 40 per book takes care of all our troubles.

**Comment by kuchlous** [comment]
@Payoshni , what do we do for all the closed and running campaigns. Their targets and percentage raised will change. I hope you are OK with that.

**Comment by Payoshni** [comment]
All the running ones can be informed and conveyed info on the change. Can you please prevent it affecting the older/closed/fully funded ones please?

**Comment by kuchlous** [comment]
@Payoshni , how about do it only for campaigns launched after today?

**Comment by Payoshni** [comment]
@kuchlous  will that solve our problem of older campaigns remaining unaffected? If yes, that will be okay!

**Comment by kuchlous** [comment]
@Payoshni , I can put any arbitrary date but today seems clean so that existing campaigns do not get affected.

**Comment by Payoshni** [comment]
okay. let's roll with it. @kuchlous

**Comment by kuchlous** [comment]
@Payoshni , Fixed. Two campaigns got started today, so their numbers have changed. Can you please inform them?

**Comment by Payoshni** [comment]
I will. Thanks Alok!


Regards,
Payoshni

“Someone reading a Book is a sign of order in the world”

-Mary Ruefle
