### ISSUE TITLE
Image not getting updated/stretching

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#277]
Have being trying since yesterday but this campaign's image is neither updating and the3 current one is majorly stretched.
Please update form the backend. (image to be updated attached-either or will do)

https://donateabook.org.in/campaign/74
![img_6248](https://cloud.githubusercontent.com/assets/12147445/9433829/41c3c266-4a55-11e5-86aa-2788ddde3b04.jpg)
![img_6242](https://cloud.githubusercontent.com/assets/12147445/9433830/41c8bbd6-4a55-11e5-8e7e-8f691ca34ae6.jpg)

**Comment by kuchlous** [comment]
@Payoshni , what image do you want to put?

**Comment by Payoshni** [comment]
either of the two attached. One is already there but is very very
stretched. The other one I am not able to update from the backend.


Regards,
Payoshni

“Someone reading a Book is a sign of order in the world”

-Mary Ruefle

**Comment by kuchlous** [comment]
Try once again. It may not update but I will get the error..

**Comment by Payoshni** [comment]
just tried again. did not get updated again. https://donateabook.org.in/campaign/74

**Comment by kuchlous** [comment]
Fixed..
