### ISSUE TITLE
Changes on Donation page: Urgent

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#278]
After the change in the average book amount, this needs to be changed too:

Rs. 1000 (28 books) to be changed to  Rs. 1000 (25 books)
Rs. 500 (14 books) to be changed to  Rs. 500 (12 books)
Rs. 250 (7 books) to be changed to  Rs. 250 (6 books)

![image](https://cloud.githubusercontent.com/assets/12147445/9439330/95269478-4a83-11e5-92f5-f3a10dc43c43.png)

**Comment by kuchlous** [comment]
Fixed..
