### ISSUE TITLE
Success stories to be updated

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#279]
Title: Books Made Their Way to Deepalaya Community Library in Sheikh Sarai
Text: Deepalaya Community Library's campaign for fundraising for books on Donate-a-Book was a roaring success where they had received 100% funding just half-way through the campaign period.Pronto multiple boxes of English and Hindi books that they had handpicked were delivered to them, part of which was their second library in Sanjay Colony.
Deepalaya Community Library serves the residents of the Sheikh Sarai and surrounding neighbourhoods with a collection of 3000 plus books and a volunteer and member run Reading Project, which is an effort to read aloud to children. The children were visibly excited by seeing the sheer number of boxes of books which was a result of the online fundraising campaign. 

To be linked to: http://blog.prathambooks.org/2015/08/as-books-made-their-way-to-deepalaya.html

![image](https://cloud.githubusercontent.com/assets/12147445/9439416/596090b4-4a84-11e5-8cb7-e7a8923f8790.png)

**Comment by kuchlous** [comment]
Please get it proof-read. I can spot some issues..

**Comment by Payoshni** [comment]
oka will get edited and confirm.

**Comment by Payoshni** [comment]
@kuchlous  Edited version

Title: So many more amazing books for children to read at the Deepalaya Community Library in Sheikh Sarai

Text: Deepalaya Community Library's campaign to raise funds for children's books through Donate-a-Book has been a roaring success. Isn't it amazing that just halfway into their campaign, they had already received 100% funding? Within two weeks, books - handpicked by members of Deepalaya - were on its way to two of their centres in Delhi. We've been told that children were visibly excited upon seeing the sheer number of boxes filled with books for them, all made possible through their online fund-raising campaign. 
Deepalaya Community Library serves the residents of Sheikh Sarai and surrounding neighbourhoods with a collection of over 3000 books. With the support of their members and volunteers, they also run the Reading Project which has a strong focus on reading aloud to children.

**Comment by kuchlous** [comment]
Fixed..
