### ISSUE TITLE
Updates and addition in Donor FAQs

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#280]
https://donateabook.org.in/about : FAQs for donors

Update FAQ no.3 as this:
3. How can I be sure the organisation that I am donating to is genuine? 
Before a campaign is live on the platform, we do a background check on the applying beneficiaries to ensure that only real and genuine organisations feature on Donate-a-Book. 
The due diligence is carried out in these two steps:
Step1: By looking up the organisation's website/Facebook page /Blog and doing a bit of research on their content and footprint.
Step 2: By contacting people working at the organisation through the phone numbers provided by them. We usually ask them to elaborate a little on the work they do, alongside gauging their plans for this funding.

This is to ensure that your money goes to a genuine organisation in need of books.
Please note, due to a small team with base only in two cities, we DO NOT do any physical verification of the beneficiaries. However, we have been working in the development sector now for over 10 years and either know most of these organisations, or are able to verify their authenticity through our network.

add faq no 13 as this:
13. I want a Tax Exemption Receipt for my donation. How and when will it reach me?
If you have opted to get the Tax Exemption Receipt by clicking 'yes' in the donor form, you are on our list. We are currently looking to automate the Tax Exemption Receipt system on the website, post which you will get e-receipts of all your donations on Donate-a-Book. This automation will take a little while and we are looking at issuing receipts post October 2015. In case you require a receipt before that, please write to donateabook@prathambooks.org and we will ensure a physical receipt reaches you within 6-7 working days. 

![image](https://cloud.githubusercontent.com/assets/12147445/9492086/f6daefea-4c11-11e5-98bb-1743984e0a14.png)

**Comment by Payoshni** [comment]
@kuchlous  Can this be closed by this weekend please? Getting too many queries for tax exemption certificate.

**Comment by kuchlous** [comment]
Done. Please check.

**Comment by Payoshni** [comment]
perfect. thanks
