### ISSUE TITLE
DAB emails inconsistently going to Donors and also new sign ups

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#283]
![image](https://cloud.githubusercontent.com/assets/12147445/9810155/fc6fdbd8-588b-11e5-9b1d-36efbd6f8b3b.png)

**Comment by kuchlous** [comment]
I think it was only a problem with gmail. Should be fixed now.

**Comment by Payoshni** [comment]
anyway to send out emails that had not gone previously?

**Comment by kuchlous** [comment]
No.
