### ISSUE TITLE
Replace the Become a Reading Champion box in the bottom panel

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#286]
Update this box with the award.
Pic sent on email.

Text to be updated to:

Donate-a-Book won the  Publishing Innovation of the Year 2015  for its ability to successfully leverage crowdsourcing and social media towards achieving its goal, as well as for an innovative initiative that demonstrates a commitment to children's books, both in Indian Languages and English.

**Comment by kuchlous** [comment]
Fixed.
