### ISSUE TITLE
Problem with a campaign's donation channel

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#287]
@kuchlous Can look into this please?

Dear Sir/Madam, 

I have a live DAB campaign set up http://donateabook.org.in/campaign/88 but unfortunately many of my family and friends have been unable to donate. They have been receiving error messages such as 'transaction not found'. Your attention to this matter would be greatly appreciated. 

Thanks, 
Swathi Nirmal

**Comment by kuchlous** [comment]
Just donated and it works fine. Ask them to try again, if they face error please send a screenshot.

Closing.
