### ISSUE TITLE
Change in the email text going out to Donors.

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#293]
Need to add a bit about the Tax exemption receipt bit. Please change the text as follows:

Subject : Thank you for helping India’s children read.
 
Dear ________________,
Thank you for donating to <insert campaign name> on Pratham Books’ Donate-a-Book platform. You are helping India’s children read. 
Help us build a reading India. You can check out similar campaigns here : https://donateabook.org.in/donate

Please note: We are currently looking to automate the Tax Exemption Receipt system on the website, post which you will get e-receipts of all your donations on Donate-a-Book. This automation will take a little while and we are looking at issuing receipts post November 2015. In case you require a receipt before that, please write to donateabook@prathambooks.org and we will ensure a physical receipt reaches you within 6-7 working days.

Regards,
Donate-A-Book Team

**Comment by kuchlous** [comment]
Fixed.
