### ISSUE TITLE
Add choice amount Rs.2500/- to the Donor form

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#295]
Hi @kuchlous 
Please add Rs.Rs.2500/- to the Donor form like this. This should go up on 22nd midnight or 23rd before 11.00 a.m

Rs.2500 (Light up a Life!)

Light up a life to be linked to : https://3399608674983039859_4539a525f095b66892e23860b4a14997568fde4c.blogspot.com/b/post-preview?token=GdR8ilABAAA.vWH9NM4E6tezaIPMCatMZJwG5rIqtUvs5R8QO4ayThm_KeuHd1OFYj7J3nUAbBLmaOSiH3taxRrdRwkEudg9wg.G-4VjlafR1ado6y_wWbj3w&postId=5104916184647443068&type=POST

**Comment by kuchlous** [comment]
Deployed..
