### ISSUE TITLE
Update Homepage banner

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#296]
Need to add a campaign specific banner in the homepage. Sending via email.
To stay on till 08-11-2015

**Comment by kuchlous** [comment]
@Payoshni , a couple of questions:

1. When to deploy?
2. What does it link to?

**Comment by Payoshni** [comment]
So sorry, in my hurry, forgot.

Deploy: right away
to be linked to:
http://blog.prathambooks.org/2015/10/this-diwali-light-diya-light-cracker.html

Regards,
Payoshni

“Someone reading a Book is a sign of order in the world”

-Mary Ruefle

**Comment by kuchlous** [comment]
Deployed. Keeping it open for removal of the banner on 08-11.

**Comment by Payoshni** [comment]
Hi @kuchlous 
Please remove this banner asap. Campaign ended on 8th.

**Comment by kuchlous** [comment]
Removed. Closing.
