### ISSUE TITLE
Each campaign to open up in a new tab under DONATE Page

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#301]
Right now, opens in the same window. Needs to open as a new tab and NOT leave the donate page.

**Comment by purvishah77** [comment]
alok is this fixed?

**Comment by purvishah77** [comment]
I suggest we keep DAB bugs here. I will figure out a priortization mechanism on our bug prioritization sheet.

**Comment by kuchlous** [comment]
Yes.

**Comment by purvishah77** [comment]
perfect thanks

**Comment by purvishah77** [comment]
perfect thanks
