### ISSUE TITLE
Old Campaigns to be re-opened

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#309]
Old campaigns to be re-opened by subtracting the already raised funds so that it does not disrupt any backend calculations.

Can it be done @kuchlous ?
Looping in @purvishah77

**Comment by kuchlous** [comment]
@Payoshni , Do you mean reopened with '0' raised and targets reset after subtracting what they have already raised?

e.g.

Original target: 20000
Raised : 8000

New balance: 0
New Target: 12000

**Comment by Payoshni** [comment]
yes. That way backend is unaffected and we dont have to tell the
beneficiary to re set a campaign.

Regards,
Payoshni

“Someone reading a Book is a sign of order in the world”

-Mary Ruefle

**Comment by Payoshni** [comment]
@purvishah77  tagging you here to raise priority for this.

**Comment by purvishah77** [comment]
@kuchlous hi alok can we take this up on priority. I will add it to the bug tracker.

**Comment by purvishah77** [comment]
@kuchlous added to bug tracker.

**Comment by kuchlous** [comment]
OK.

**Comment by Payoshni** [comment]
@kuchlous Can we get these campaigns opened by January 3rd/4th please?

cc @purvishah77

**Comment by kuchlous** [comment]
Do you have any particular campaigns in mind? Or do you need the general
functionality?

**Comment by Payoshni** [comment]
I could give you a list of campaigns to be opened. Or if you want to add functionality, either is okay. Functionality might be a better long term solution.

**Comment by kuchlous** [comment]
Aiming to add general functionality. Will ask for campaigns if
functionality is not ready.

**Comment by Payoshni** [comment]
okay.

**Comment by kuchlous** [comment]
@sandeepgoud , Is this complete for deployment?

**Comment by sandeepgoud** [comment]
yes sir, completed and i have sent pull request to you.
