### ISSUE TITLE
DAB site seems to have gone back to its test mode: URGENT

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#318]
Dummy Pictures and dummy text shown

![image](https://cloud.githubusercontent.com/assets/12147445/14417490/d24e1762-ffd3-11e5-87af-6bbd9fcff345.png)

**Comment by kuchlous** [comment]
Because you do not have any open campaigns. All the campaigns are either fully funded or closed.

**Comment by kuchlous** [comment]
Should I change it to show closed campaigns?

**Comment by purvishah77** [comment]
@Payoshni re-open old campaigns asap??

**Comment by Payoshni** [comment]
just approved one campaign, will reopen a couple of old ones. Wow, didnt
imagine this problem.


Regards,
Payoshni

“Someone reading a Book is a sign of order in the world”

-Mary Ruefle
