### ISSUE TITLE
Immediate text change in the Beneficiary form

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#319]
Beneficiary Form, Step 2, Get started-Please change these two lines:

First Section-
Line 1: Note - Each LIC kit contains approximately 125 books.
CHANGE TO
Note - Each LIC kit contains books worth Rs.4500/- and Rs.500/- goes towards packaging and handling.

Second Section-
Line 2- 
PLEASE NOTE: The fund-raising amount includes the cost of books and the shipping charges so that you don't have to pay anything more or incur extra costs. However, Pratham Books reserves the right to adjust the number of books being sent to you depending on the MRP of the books chosen by you, the inventory levels and the final amount that your campaign raises.
CHANGE TO-
PLEASE NOTE: The fund-raising amount includes the cost of books and the shipping charges. However, Pratham Books reserves the right to adjust the number of books being sent to you depending on the MRP of the books chosen by you, the inventory levels and the final amount that your campaign raise

Reference- 

![image](https://cloud.githubusercontent.com/assets/12147445/16263155/73ef8d04-3890-11e6-9b01-e389c2e7f588.png)

**Comment by kuchlous** [comment]
Fixed.
