### ISSUE TITLE
Change the DAB Banner

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#321]
The Donate-a-Thon banner to go.
![Uploading image.png…]()

In place, add this (attached)
Not to be linked anywhere
![donate-a-book banner for the web 230615_02](https://cloud.githubusercontent.com/assets/12147445/16332605/60c381ba-3a14-11e6-896d-cdfc566a3fb1.jpg)

**Comment by kuchlous** [comment]
Done.
