### ISSUE TITLE
Need an easy way to remove search parameters

### ISSUE THREAD

**Issue by kuchlous** [PrathamBooks/frp#35]
When the user searches he reaches a page with filtered items. Need a way to go back to unfiltered results.

**Comment by kuchlous** [comment]
At least filters are easy to remove now. Need something to remove search params as well.

**Comment by kuchlous** [comment]
Sandeep, need to position the "Show All Campaigns" link properly. Check out:

http://donateabook.org.in/search?search-string=karnal

**Comment by pvsandeep** [comment]
Remove the link from search section

<form action="/search" class="discover-search" method="GET">
      <div id="search" class="input-group">
        <a href="/discover"> Show All Campaigns </a><br><br>
        <input type="text" class="form-control" name="search-string"
placeholder="karnal">
        <input type="submit" value="" class="icon-search">
      </div>
    </form>


Place the link under

<div class="col-md-12">
<h2>Discover campaigns now </h2>
*<div class="showAll pull-right"><i class="icon-large icon-th"></i><a
href="/discover"> Show All Campaigns </a></div>*
</div>


*Update css code:*

.showAll.pull-right {
  padding: 27px 20px 10px;
}
i.icon-large.icon-th {
  background-position: 231px 0px;
}

.showAll.pull-right a {
  font-size: 12px;
  display: inline-block;
  vertical-align: sub;
  margin-left: 3px;
}


[image: Inline image 1]

On Fri, May 15, 2015 at 4:27 PM, AK <notifications@github.com> wrote:

> Sandeep, need to position the "Show All Campaigns" link properly. Check
> out:
>
> http://donateabook.org.in/search?search-string=karnal
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/35#issuecomment-102369105>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
This is fine.
