### ISSUE TITLE
Message for Fully Funded Campaigns

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#51]
Can we add a message for Fully fund campaigns when someone clicks on the donate button? Can be a hover text too.

 'This campaign is now fully funded and is not open to receive any more donations.Check out similar campaigns' (with a link to similar campaigns if possible

**Comment by kuchlous** [comment]
Implemented. Assigned to Sandeep for styling of 'Similar Campaign' button. To see, go to:

http://donateabook.org.in/campaign/1

and click on "Donate to this campaign".
