### ISSUE TITLE
Beneficiary form movement

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#54]
While moving from Step 1 to Step 2 of the Beneficiary Form, if a user has left cells blank, not filled in required info, the system to:

1.Highlight the blank boxes in an orange glow
2.Have a message pop-up which says 'You have left some columns empty on this page. Please fill in all columns of this step to move to the next step'

**Comment by kuchlous** [comment]
Fixed. Check if the error message looks ok.
