### ISSUE TITLE
donate-a-book to be written in all small letters

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#56]
Please change if written in any other way across the platform and communication
Platform: am doing in copy
Email : AK-Can you change it please.

correct way to write: donate-a-book (in bold wherever possible)
 In thebrowser tab too please.  (refer screenshot)

![image](https://cloud.githubusercontent.com/assets/12147445/7409673/f616eb96-ef45-11e4-8fba-3a091407df09.png)

**Comment by kuchlous** [comment]
Fixed including in emails. Now the end of emails is:

Regards
donate-a-book team
