### ISSUE TITLE
BF Preview

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#59]
seems off. Fields are hither-tither
refer screen shot

![image](https://cloud.githubusercontent.com/assets/12147445/7410274/efad3422-ef4a-11e4-8319-d452c05adff0.png)

**Comment by Payoshni** [comment]
also BF Preview does not show the main story?

**Comment by Payoshni** [comment]
ALOK : we havent thought through the Preview form. We dont need to show the contact details of person in the preview as that isNOT what is visible on the campaign page. Reworking this text and sharing

**Comment by kuchlous** [comment]
Assigned to Sandeep for the field alignment issues.

**Comment by Payoshni** [comment]
let's change the text first. updated In my copy review.

**Comment by kuchlous** [comment]
Fixed. Even styling looks OK now. Please check.
