### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#60]
1 mb is too less a size. Can make it upto 5 mb atleast? or anything else you suggest, but 1 mb too less in my opinion. refer screenshot

![image](https://cloud.githubusercontent.com/assets/12147445/7410397/11387b50-ef4c-11e4-8e73-c44b580c60bc.png)

**Comment by kuchlous** [comment]
OK. But remember that the larger the files, the more time to upload and again more to download the page - we are not doing any processing in the backend to make the files smaller.

**Comment by Payoshni** [comment]
so lets keep to 2 mb. Usually camera shot pics are between that range. should work.

**Comment by kuchlous** [comment]
Fixed.
