### ISSUE TITLE
Abandoning the BF

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#61]
A user can by mistake or purposely close, escape,abandon the beneficiary form midway. We need to have an Alert message here. The message to read

'You haven't submitted your form yet.The form will not be saved. Are you sure you want to leave this page?'

on the same lines Alok, do we have a auto save or a save form feature for later edits? If not, should we say that somewhere?

**Comment by kuchlous** [comment]
OK, we will add an alert.

We do not have an auto save. We can do that later in next rev. We can say that in the alert.

**Comment by Payoshni** [comment]
message up[dated with the Not saved alert

**Comment by kuchlous** [comment]
Browsers do not allow to give an alert or message on leaving a page. We will add auto-save in next phase. For now we just need to add it somewhere else. Not sure where.

**Comment by kuchlous** [comment]
Added a pop-up on leaving the page.
