### ISSUE TITLE
Donate buttons on discover page should have same style as the donate button on individual campaign page 

### ISSUE THREAD

**Issue by kuchlous** [PrathamBooks/frp#63]

**Comment by pvsandeep** [comment]
update css code:


.modal-content button.btn {
  background: #ffc600;
  border-radius: 29px;
  text-transform: uppercase;
  font-family: "ligurino-condensed", sans-serif;
  font-size: 16px;
  letter-spacing: 2px;
}

On Mon, May 4, 2015 at 5:03 PM, AK <notifications@github.com> wrote:

> Assigned #63 <https://github.com/PrathamBooks/frp/issues/63> to @pvsandeep
> <https://github.com/pvsandeep>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/63#event-296163265>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
This actually fixes 51, not 63.

**Comment by pvsandeep** [comment]
sorry for #63

update line no: 11153

#internalCampaign.singleCamp .campaignInfo h5.amt {

  border-radius: 29px;
  text-transform: uppercase;
  letter-spacing: 2px;
  font-size: 1.8em;
  font-weight: normal;
  background-color: #ffc600;
}

On Mon, May 11, 2015 at 5:22 PM, AK <notifications@github.com> wrote:

> This actually fixes 51, not 63.
>
> On Mon, May 11, 2015 at 4:51 PM, pvsandeep <notifications@github.com>
> wrote:
>
> > update css code:
> >
> >
> > .modal-content button.btn {
> > background: #ffc600;
> > border-radius: 29px;
> > text-transform: uppercase;
> > font-family: "ligurino-condensed", sans-serif;
> > font-size: 16px;
> > letter-spacing: 2px;
> > }
> >
> > On Mon, May 4, 2015 at 5:03 PM, AK <notifications@github.com> wrote:
> >
> > > Assigned #63 <https://github.com/PrathamBooks/frp/issues/63> to
> > @pvsandeep
> > > <https://github.com/pvsandeep>.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/PrathamBooks/frp/issues/63#event-296163265>.
> > >
> >
> >
> >
> > --
> > Thanks,
> > Sandeep
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/PrathamBooks/frp/issues/63#issuecomment-100873424>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/63#issuecomment-100885022>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
This does not seem to fix anything.

**Comment by pvsandeep** [comment]
I have applied css code for http://donateabook.org.in/campaign/2  page. See
the attached screen shot.





On Mon, May 11, 2015 at 5:50 PM, AK <notifications@github.com> wrote:

> This does not seem to fix anything.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/63#issuecomment-100889955>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
I was thinking of modifying the donate button on "discover" page to match
the button on the campaign page.

I like the existing style on the campaign page.

**Comment by pvsandeep** [comment]
Add the css code

#campaigns .col-md-3 .browse-btn {
  background-color: #ffe538!important;
  border-radius: 3px!important;
  font-size: 2.5em!important;
  letter-spacing:0 !important;
  text-transform: capitalize!important;
  color: #606060!important;
  padding: 2px 20px!important;
}

On Mon, May 11, 2015 at 7:22 PM, AK <notifications@github.com> wrote:

> I was thinking of modifying the donate button on "discover" page to match
> the button on the campaign page.
>
> I like the existing style on the campaign page.
>
> On Mon, May 11, 2015 at 6:03 PM, pvsandeep <notifications@github.com>
> wrote:
>
> > I have applied css code for http://donateabook.org.in/campaign/2 page.
> See
> > the attached screen shot.
> >
> >
> >
> >
> >
> > On Mon, May 11, 2015 at 5:50 PM, AK <notifications@github.com> wrote:
> >
> > > This does not seem to fix anything.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/PrathamBooks/frp/issues/63#issuecomment-100889955
> >.
> >
> > >
> >
> >
> >
> > --
> > Thanks,
> > Sandeep
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/PrathamBooks/frp/issues/63#issuecomment-100891680>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/63#issuecomment-100915689>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
The button is not centered.

**Comment by pvsandeep** [comment]
Update css code

#campaigns .col-md-3 .browse-btn {
  background-color: #ffe538!important;
  border-radius: 3px!important;
  font-size: 2.5em!important;
  letter-spacing: 0 !important;
  text-transform: capitalize!important;
  color: #606060!important;
  padding: 2px 20px!important;
  margin: 0 33% !important;
  float: inherit !important;
}

On Mon, May 11, 2015 at 8:02 PM, AK <notifications@github.com> wrote:

> The button is not centered.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/63#issuecomment-100926827>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
OK, Got it.
