### ISSUE TITLE
Need a badge for featured campains

### ISSUE THREAD

**Issue by kuchlous** [PrathamBooks/frp#64]
Just like we have a badge for Fully funded, need a badge for featured. May be a star. Or we make fully funded a new badge and use the current badge for featured. Also need to decide on the positioning.

**Comment by Payoshni** [comment]
Icon attached

![featured-color 1](https://cloud.githubusercontent.com/assets/12147445/7630188/6701ff24-fa51-11e4-9347-0c1f524f54f5.png)

**Comment by pvsandeep** [comment]
<span class="featured-campaign">featured</span>

Add css code:

span.featured-campaign {
    background-image: url("../images/featured-champion.png");
    background-position: right 5px;
    background-repeat: no-repeat;
    background-size: 41px auto;
    color: #222222;
    float: right;
    font-size: 8px;
    margin: -24px -12px 0 0;
    padding: 29px 0 5px;
    position: absolute;
    right: 0;
    text-transform: uppercase;
    width: 78px;
}


On Thu, May 14, 2015 at 3:54 PM, Payoshni <notifications@github.com> wrote:

> Icon attached
>
> [image: featured-color 1]
> <https://cloud.githubusercontent.com/assets/12147445/7630188/6701ff24-fa51-11e4-9347-0c1f524f54f5.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/64#issuecomment-101995892>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
Wjat image should I use? The one Payoshni supplied?

**Comment by pvsandeep** [comment]
Use my image.

On Fri, May 15, 2015 at 11:24 AM, AK <notifications@github.com> wrote:

> Wjat image should I use? The one Payoshni supplied?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/64#issuecomment-102269592>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
Two problems:

1. Image does not have a transparent background.
2. If a campaign is also fully funded the icons overlap.
![screen shot 2015-05-15 at 11 28 02 am](https://cloud.githubusercontent.com/assets/1202539/7647605/799ee1de-faf5-11e4-9420-270de87153ab.png)

**Comment by pvsandeep** [comment]
Update css code;

*line no: 11132*

.internal #internalCampaign.discover span.champion {
    margin: -25px -12px 0 15px;
    position: relative;
    right: 0;
    width: 66px;
}

*add new css code*

span.featured-campaign {
    background-image: url("../images/featured-champion.png");
    background-position: right 5px;
    background-repeat: no-repeat;
    background-size: 41px auto;
    color: #222222;
    float: right;
    font-size: 8px;
    margin: -24px -12px 0 0;
    padding: 29px 0 5px;
    position: relative;
    right: 0;
    text-transform: uppercase;
    width: 78px;
}


On Fri, May 15, 2015 at 11:29 AM, AK <notifications@github.com> wrote:

> Two problems:
>
>    1. Image does not have a transparent background.
>    2. If a campaign is also fully funded the icons overlap. [image:
>    screen shot 2015-05-15 at 11 28 02 am]
>    <https://cloud.githubusercontent.com/assets/1202539/7647605/799ee1de-faf5-11e4-9420-270de87153ab.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/64#issuecomment-102269980>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
Better. Just fix the transparency.

**Comment by pvsandeep** [comment]
I have already attached in last mail or find the attachment.

On Fri, May 15, 2015 at 12:04 PM, AK <notifications@github.com> wrote:

> Better. Just fix the transparency.
>
> On Fri, May 15, 2015 at 12:00 PM, pvsandeep <notifications@github.com>
> wrote:
>
> > Update css code;
> >
> > *line no: 11132*
> >
> > .internal #internalCampaign.discover span.champion {
> > margin: -25px -12px 0 15px;
> > position: relative;
> > right: 0;
> > width: 66px;
> > }
> >
> > *add new css code*
> >
> > span.featured-campaign {
> > background-image: url("../images/featured-champion.png");
> > background-position: right 5px;
> > background-repeat: no-repeat;
> > background-size: 41px auto;
> > color: #222222;
> > float: right;
> > font-size: 8px;
> > margin: -24px -12px 0 0;
> > padding: 29px 0 5px;
> > position: relative;
> > right: 0;
> > text-transform: uppercase;
> > width: 78px;
> > }
> >
> >
> > On Fri, May 15, 2015 at 11:29 AM, AK <notifications@github.com> wrote:
> >
> > > Two problems:
> > >
> > > 1. Image does not have a transparent background.
> > > 2. If a campaign is also fully funded the icons overlap. [image:
> > > screen shot 2015-05-15 at 11 28 02 am]
> > > <
> >
> https://cloud.githubusercontent.com/assets/1202539/7647605/799ee1de-faf5-11e4-9420-270de87153ab.png
> > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/PrathamBooks/frp/issues/64#issuecomment-102269980
> >.
> >
> > >
> >
> >
> >
> > --
> > Thanks,
> > Sandeep
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/PrathamBooks/frp/issues/64#issuecomment-102282405>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/64#issuecomment-102283286>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
OK. Working now. Updated on http://104.155.192.202/. Will update on d-a-b later.
