### ISSUE TITLE
Send emails to the login email id, the info id as well as the contact person id

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#66]
All emails should go to all three ids. Exact reason why we asked for all three.

**Comment by kuchlous** [comment]
Fixed. Note that we do not have the contact person info in the beneficiary form now so the email will go to login email and org info email.

**Comment by kuchlous** [comment]
Contact person added in (was removed by a typo in html comment). Added sending emails to contact person as well.
