### ISSUE TITLE
Arrow at bottom of discover page not aligned properly

### ISSUE THREAD

**Issue by kuchlous** [PrathamBooks/frp#70]
Look at

http://donateabook.org.in/discover

![screen shot 2015-05-09 at 12 01 59 pm](https://cloud.githubusercontent.com/assets/1202539/7549034/3b876d32-f643-11e4-96b5-b56e5fb00e42.png)

**Comment by pvsandeep** [comment]
Replace Html code

<div class="col-md-9">
      <button id="scroll" type="button" class="btn btn-default
btn-bottom">Default</button>
    </div>

to

<div class="*col-md-12*">
      <button id="scroll" type="button" class="btn btn-default
btn-bottom">Default</button>
    </div>




Add css code:

#internalCampaign.discover .col-md-12 #scroll.btn-bottom {
    left: inherit !important;
    right: 18px;
}

On Sat, May 9, 2015 at 12:03 PM, AK <notifications@github.com> wrote:

> Assigned #70 <https://github.com/PrathamBooks/frp/issues/70> to @pvsandeep
> <https://github.com/pvsandeep>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/70#event-300796638>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
OK, looks good.

**Comment by kuchlous** [comment]
Vanished with the new changes. Likely I made some
