### ISSUE TITLE
Featured button is bigger with a star

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#75]
![image](https://cloud.githubusercontent.com/assets/12147445/7628164/62519e62-fa3d-11e4-8fb3-3c270ce94a32.png)

**Comment by kuchlous** [comment]
The Featured next to the star is just a title - not a link. Should we
replace it with "More Campaigns"

**Comment by kuchlous** [comment]
Changed this to "More Campaigns". Check out now at 

http://donateabook.org.in/campaign/4
