### ISSUE TITLE
Add time left on discover page

### ISSUE THREAD

**Issue by kuchlous** [PrathamBooks/frp#79]
We need to add an indication of the time left on discover page just like we do on the campaign page and the beneficiary/donor dashboards.

This is specially needed when user sorts on "Ending Soon/Recently Launched", without an indication of the time left it is difficult to make sense of the sorting.

Sandeep, look at:

http://donateabook.org.in/campaign/1

There is time left with the clock icon. Need something similar on the discover page cards. Once you give me the html/css, I can add the backend support easily.

**Comment by pvsandeep** [comment]
Html code

*<time><span>29 </span> Days Left</time>*" add this line after <h6>Funding
Details</h6>.

<h6>Funding Details</h6>
<time><span>29 </span> Days Left</time>

attached css code for both #79 and #88

On Sun, May 17, 2015 at 9:43 AM, AK <notifications@github.com> wrote:

> Assigned #79 <https://github.com/PrathamBooks/frp/issues/79> to @pvsandeep
> <https://github.com/pvsandeep>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/79#event-306665563>.
>



-- 
Thanks,
Sandeep

lineno: 11150



.internal #internalCampaign.discover span.champion {
  margin: -25px -12px -27px 15px;
  position: relative;
  right: 0;
  width: 66px;
}


lineno: 10209

span.featured-campaign {
  background-image: url("../images/featured-champion.png");
  background-position: right 5px;
  background-repeat: no-repeat;
  background-size: 41px auto;
  color: #222222;
  float: right;
  font-size: 8px;
  margin: -24px -12px -20px 0;
  padding: 29px 0 5px;
  position: relative;
  right: 0;
  text-transform: uppercase;
  width: 78px;
}


#internalCampaign #campaigns .col-md-3 h2 {
 
  min-height: 57px;
}

.internal .col-md-9 .col-md-3 {
  min-height: initial;
  padding: 0 0 30px;}


 #campaigns .internal time {
 
  font-size: 1.5em;
 margin: 0px 0 12px;
  padding: 0 0 4px 32px;
  background-size: 24px;
}


#campaigns .col-md-3 .campaignInfo p {
  min-height: 40px;
}


#campaigns .campaignInfo h6 {
  margin: 0px 0 10px !important;
}

**Comment by kuchlous** [comment]
Sandeep, this did not work. Checkout:

http://104.155.192.202/discover

**Comment by pvsandeep** [comment]
Updated css code

*line no: 11171*

.internal #internalCampaign.discover span.champion {
  margin: -25px -12px -26px 15px;
  position: relative;
  right: 0;
  width: 66px;
}

*line no: 9723 *

.internal .col-md-9 .col-md-3 {
  width: 31.7%;
  height: auto;
  border: 1px solid #bdae85;
  background-color: #fafafa;
  margin: 0 6px 30px;
  padding: 0 0 30px;
}

On Mon, May 18, 2015 at 10:45 PM, AK <notifications@github.com> wrote:

> Sandeep, this did not work. Checkout:
>
> http://104.155.192.202/discover
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/79#issuecomment-103138829>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
This seems to work.
