### ISSUE TITLE
flash messages need styling

### ISSUE THREAD

**Issue by kuchlous** [PrathamBooks/frp#83]
We need to style the flash messages properly. Right now they show up shown in the screenshot.
![screen shot 2015-05-18 at 1 43 08 pm](https://cloud.githubusercontent.com/assets/1202539/7676708/d7c7fca8-fd63-11e4-926b-b2de37f761de.png)

**Comment by pvsandeep** [comment]
Update css code

line no:11511

.flashes li {
  padding: 15px;
  font-weight: bold;
  max-width: 360px;
  margin: 0px auto;
  margin-bottom: 1%;
  width: 90%;
  background-color: rgba(255,255,255,.8);
  box-shadow: 1px 2px 5px #555;
}


line no:11503

.flashes {
  text-align: center;
  margin: 2% 0px;
  font-size: 1.2em;
  position: absolute;
  width: 100%;
  z-index: 1;
}


line no:11542

#wrapperOut #wrapper {
  width: 100%;
  max-width: 1200px;
  position: relative;
}

[image: Inline image 1]

On Mon, May 18, 2015 at 4:13 PM, AK <notifications@github.com> wrote:

> Assigned #83 <https://github.com/PrathamBooks/frp/issues/83> to @pvsandeep
> <https://github.com/pvsandeep>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrathamBooks/frp/issues/83#event-307256255>.
>



-- 
Thanks,
Sandeep

**Comment by kuchlous** [comment]
This is better but I would like the notifications to be dismissable like
what bootstrap has. Can you please integrate with bootstrap notification
system and let me know the changes?

**Comment by pvsandeep** [comment]
*HTML Code update*

<ul class="flashes">
<li class="alert-success">You have signed in successfully.
<a href="#" class="close" data-dismiss="alert">×</a>
</li>
</ul>




*line no:11503*

.flashes {
text-align: center;
margin: 0  auto;
font-size: 1.2em;
position: absolute;
z-index: 1;
width: 100%;
}

*line no:11511*

.flashes li {
padding: 15px;
font-weight: bold;
max-width: 360px;
margin: 0px auto;
width: 90%;
box-shadow: 0px 0px 10px #444;
position:relative;
}

.flashes a.close {
position:absolute;
  right: 10px;
  top: 11px;
  color: #000;
  opacity: 0.7;
}

*line no:11542*

#wrapperOut #wrapper {
  width: 100%;
  max-width: 1200px;
  position: relative;
}


[image: Inline image 1]

**Comment by kuchlous** [comment]
OK, Looks good.
