### ISSUE TITLE
multi select button

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#84]
This is a multi select button: (not a single option)

![image](https://cloud.githubusercontent.com/assets/12147445/7679524/27e05796-fd7b-11e4-9aa5-52734d7d0723.png)

**Comment by kuchlous** [comment]
This was just an error message problem but I just realized that we do not even use this info anywhere. Neither in the campaign page, nor in the discover page. Why are we even getting it?

**Comment by Payoshni** [comment]
This was earlier to be part of the selection filter under TYPE. But over time, it was dropped (as a selection filter).
Let it be as of now. We may use it in Ver 2.
