### ISSUE TITLE
Info disappearence

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#85]
Every time there is an error and you go back to correct it and then come back on the third page, the City info & the image disappears (along with the multi select impact boxes)

![image](https://cloud.githubusercontent.com/assets/12147445/7679554/9fb29964-fd7b-11e4-9876-90550f71924a.png)

**Comment by kuchlous** [comment]
City is fixed. Not sure if image can be fixed at all. Will check.

**Comment by kuchlous** [comment]
Need to check on preservation of the organization work multi-select also.

**Comment by kuchlous** [comment]
Image and org-work still do not work. Will fix later.

**Comment by kuchlous** [comment]
Except for image, everything should work now.
