### ISSUE TITLE
Incorrect error messages

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#86]
All error messages incorrect. All the word limit is in words now, not characters. It is mentioned below the box, this should be the error msg (Not more than 100 words not more than 150 words etc)

![image](https://cloud.githubusercontent.com/assets/12147445/7679588/f1037ffe-fd7b-11e4-86da-9be3925f8e8c.png)

**Comment by kuchlous** [comment]
Made the character limits large so will not see this error. Still need to add word limits so keeping this open.

**Comment by kuchlous** [comment]
Also the boxes are not getting marked when returning from the server.

**Comment by kuchlous** [comment]
Added proper errors to javascript. Will add to the backend in next phase as the user is not likely to see them.

**Comment by kuchlous** [comment]
This should be fixed now..
