### ISSUE TITLE
Trying to submit the beneficiary form multiple times. keeps taking me back to Step 1

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#87]

**Comment by kuchlous** [comment]
My guess is that the checkbox under "Do you or your organization do any work for following" was left unchecked. For some reason on error it shows as selected but the backend does not get it. Hopefully if you get the error now I will know the cause as I have turned on error messages in the backend for this situation.

**Comment by kuchlous** [comment]
@Payoshni Are you still facing this problem. If not, please close.

**Comment by Payoshni** [comment]
No, works perfectly now. Closing
