### ISSUE TITLE
Change in the backend + line

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#99]
Need to change the backend calculation for funds basis number of books.

The final calculation is:
Number of books x Rs.36.75 = Fundraising amount.

This calculation will not be visible to the beneficiary. This is how the block should look:

Number of Books: XXX
Fundraising amount : Rs.XXXX

Please note: The fundraising amount includes cost of books and the shipping charges. Pratham Books is committed to send you the maximum number of books. It however reserves the right to adjust the number of books being sent to you basis the books chosen by you, the inventory levels and the final amount raised. 

(might change this line a little bit after legal approval)

![image](https://cloud.githubusercontent.com/assets/12147445/7930125/447553c6-0923-11e5-88ba-3d470a6aa60e.png)

**Comment by kuchlous** [comment]
Fixed, Please check and get a copy check done.

**Comment by Payoshni** [comment]
Final line for this is : 

Please note: The fund-raising amount includes the cost of books and the shipping charges​ so that ​you don't​ have to pay anything more or incur extra costs. However, Pratham Books reserves the right to adjust the number of books being sent to you depending on the MRP of the books chosen by you, the inventory levels and the final amount that your campaign raises.
